config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  
    resources :users, only: [:index, :show, :new, :create] do
        member do
         get :likes
        end
    end
    
# 本の検索・閲覧
    resources :books, only: [:index, :show]
    
# お気に入り機能
    resources :users_books, only: [:create, :destroy]
   
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  # 作品用データベースとの連携
  has_many :books, through: :books_authors
  has_many :books_authors
  
end

app/models/book.rb
class Book < ApplicationRecord
# 著者用データベースとの連携
  has_many :authors, through: :books_authors
  has_many :books_authors

# ハイライトデータベースとの連携
  has_many :highlighted_paragraphs
  
# カテゴリーデータベースとの連携
  belongs_to :category
  
# お気に入り機能
  has_many :users, through: :users_books
  has_many :users_books
end

app/models/books_author.rb
class BooksAuthor < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books
end

app/models/highlighted_paragraph.rb
class HighlightedParagraph < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
# ハイライト機能
  has_many :highlighted_paragraphs

# お気に入り機能
  has_many :users_books
  has_many :likes, through: :users_books, source: :book
  has_many :reverses_of_users_books, class_name: 'Users_book', foreign_key: 'book_id'
  has_many :followers, through: :reverses_of_users_book, source: :user
  
  
  def like(other_user)
      self.users_books.find_or_create_by(book_id:other_user.id)
  end

  def dislike(other_user)
    users_book = self.users_books.find_by(book_id:other_user.id)
    users_book.destroy if users_book
  end
  
  def likes?(other_user)
    self.likes.include?(other_user)
  end



end

app/models/users_book.rb
class UsersBook < ApplicationRecord
  belongs_to :book
  belongs_to :user
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    # 検索オブジェクト
    @search = Book.ransack(params[:q])
    # 検索結果
    @books = @search.result
  end

  def show
    @book = Book.find(params[:id])
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_books_controller.rb
class UsersBooksController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    current_user.like(book)
    flash[:success] = 'お気に入りを追加しました。'
    redirect_to :back
  end

  def destroy
    @book = Book.find(params[:book_id])
    current_user.dislike(@book)
    flash[:success] = 'お気に入りを解除しました。'
    redirect_to :back
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :likes]
  
  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def likes
    @user = User.find(params[:id])
    @likes = @user.likes.page(params[:page])
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_books_helper.rb
module UsersBooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/index.html.erb
<!--検索フォーム---->
<h2>検索フォーム</h2>
<%= search_form_for @search do |f| %>
  <p>タイトル</p>
  <%= f.search_field :title_cont %>
  
  <p>著者</p>
  <%= f.search_field :authors_name_cont %>
  
  <p>カテゴリー</p>
  <%= f.search_field :category_name_cont %>
  
  <p>出版年</p>
  <%= f.search_field :publication_year_cont %>
  
  <div class="actions"><%= f.submit "検索" %></div>
<% end %>

<!--検索結果-->
<h2>作品一覧</h2>
<% @books.each do |book| %>
    <%= book.title %>  <br>
    <%= book.publication_year.strftime('%Y年') %>  <br>
    <p><%= link_to '作品へ', book_path(book) %></p>
<% end %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>

<%= simple_format(@book.content) %><br>

<!--お気に入り登録ボタン-->
<% if logged_in? %>
  <% if current_user.likes?(@book) %>
    <%= form_for(current_user.users_books.find_by(book_id: @book.id), html: { method: :delete }) do |f| %>
      <%= hidden_field_tag :book_id, @book.id %>
      <%= f.submit 'お気に入り解除' %>
    <% end %>

  <% else %>
    <%= form_for @book, url: users_books_path, method: :post do |f| %>
      <%= hidden_field_tag :book_id, @book.id %>
      <%= f.submit 'お気に入り' %>
    <% end %>

  <% end %>
<% end %>
  

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          
          <% if logged_in? %>
            <li><%= link_to 'Top Page', root_path %></li>
            <li><%= link_to 'My profile', user_path(current_user) %></li>
            
              <li role="separator" class="divider"></li>
              <li role="separator" class="divider"></li>
            <li><%= link_to 'Logout', logout_path, method: :delete %></li>
            </li>
            

          <% else %>
          <li><%= link_to 'Top Page', root_path %></li>
          
            <li role="separator" class="divider"></li>
            <li role="separator" class="divider"></li>
          <li><%= link_to 'Signup', signup_path %></li>
          <li><%= link_to 'Login', login_path %></li>
          <% end %>
          
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Aozora Viewer</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/toppages/index.html.erb
<div class="center jumbotron">
  <div class="text-center">
    <h1>ようこそ　Aozora Viewer　へ</h1>
  </div>
</div>

<h2>Aozora viewer について</h2>
  <h3>本サービスは青空文庫の作品を気軽に楽しむために作成されました。</h3>
  <li><%= link_to '検索ページへ', books_path %></li>
  
<h2>青空文庫</h2>
  <h3>青空文庫とは著作権が消滅した作品等を無料で公開しているインターネット図書館です。</h3>
  <li><%= link_to '青空文庫へ', 'https://www.aozora.gr.jp/' %></li>
  
<h2>利用できる機能</h2>
  <h3>検索：検索ページより作品を検索することができます</h3>
  <h3>お気に入り登録：お気に入りの作品を登録することができます</h3>
  <!--<h3>ハイライト登録：作品の中でも気に入ったフレーズや文章を個別に保存できます</h3>-->
  <h5>※お気に入り登録はユーザ登録が必要になります</5>
  <li><%= link_to 'ユーザー登録ページへ', signup_path %></li>

app/views/users/index.html.erb
<% if users.any? %>
  <ul class="media-list">
    <% users.each do |user| %>
      <li class="media">
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/likes.html.erb
<h1>お気に入り作品一覧</h1>

<% @user.likes.each do |like| %>
    <%= like.title %>  <br>
    <%= like.publication_year.strftime('%Y年') %>  <br>
    <p><%= link_to '作品へ', book_path(like) %></p>
<% end %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

  <%= form_for(@user) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>

      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-xs-4">
    
    <!--ユーザ名とメールアドレスを表示-->
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">名前：<%= @user.name %></h3>
      </div>
    </div>
      
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">メールアドレス：<%= @user.email %></h3>
      </div>
    </div>
    
    <!--お気に入り機能・ハイライト・検索の表示-->
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= link_to 'お気に入りページへ', likes_user_path %></h3>
      </div>
    </div>
    
    <!--<div class="panel panel-default">-->
    <!--  <div class="panel-heading">-->
    <!--    <h3 class="panel-title"><%= link_to 'ハイライトページへ', books_path %></h3>-->
    <!--  </div>-->
    <!--</div>-->
    
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= link_to '検索ページへ', books_path %></h3>
      </div>
    </div>

    
  </aside>
  <div class="col-xs-8">
  </div>
</div>